# Change these first
owner: raraby # Your GitHub username
repo: upptime # Your GitHub repository name

# Add your sites here
sites:  
  - name: Google
    url: https://www.google.com
  - name: Minecrosoft
    url: https://www.microsoft.com
  - name: Google Translate
    url: https://translate.google.co.jp
  - name: Google Photo
    url: https://photos.google.com
    icon: https://www.google.com/photos/about/static/images/logos/logo_photos_192px.png
  - name: Google Play
    url: https://play.google.com/store
    icon: https://www.gstatic.com/android/market_images/web/favicon_v2.ico
  - name: Google MAP
    url: https://www.google.co.jp/maps
  - name: Hypixel
    url: https://hypixel.net
    icon: https://hypixel.net/favicon-32x32.png
  - name: Youtube
    url: https://www.youtube.com
  - name: Discord
    url: https://discord.com/
    icon: https://discord.com/assets/07dca80a102d4149e9736d4b162cff6f.ico
  - name: Instagram
    # method: HEAD
    url: https://www.instagram.com
  - name: Minecraft
    url: https://www.minecraft.net
    icon: https://www.minecraft.net/etc.clientlibs/minecraft/clientlibs/main/resources/favicon.ico
  - name: Twitch
    url: https://www.twitch.tv
    icon: https://static.twitchcdn.net/assets/favicon-32-d6025c14e900565d6177.png
  - name: Osu
    url: https://osu.ppy.sh/home
  - name: Google Drive
    url: https://drive.google.com/drive
    icon: https://ssl.gstatic.com/images/branding/product/1x/drive_2020q4_32dp.png
  - name: Google Cloud
    url: https://console.cloud.google.com
    icon: https://www.gstatic.com/devrel-devsite/prod/ve312520032ba2ac0c4d23f7b46fc670cbbe051886a2d1f04563a5e4768ad9787/cloud/images/favicons/onecloud/super_cloud.png
  - name: OneDrive
    url: https://onedrive.live.com
  - name: GitHub
    url: https://github.com
  - name: Cloudflare
    url: https://www.cloudflare.com
  - name: Beyond Description
    url: https://raraby.github.io/BeyondDescription/
  - name: Wikipedia
    url: https://en.wikipedia.org

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: ""
  introTitle: ""
  # "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: ""
  # This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  # js: "console.log('test')"
  css: "body { opacity: 0.5 }"
  # ".svelte-ngkazm,.svelte-1sgaob0,.svelte-jbr799{display: none;} .svelte-1uadwzk{margin-top: 30px;}"
      
i18n:
  averageResponseTime: "Ping: $TIMEms"
  footer: ""

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
